#!/usr/bin/env bash
# Embed a read-only GitHub token into a release build so the updater works
# while the repo is still private.
#
#   GH_RELEASE_TOKEN=github_pat_... scripts/embed-token.sh
#   scripts/embed-token.sh --clear
#
# The token MUST be a fine-grained PAT scoped to this repository alone, with
# Contents: Read-only and no other permission. It ships inside every release
# asset, so treat it as public: anyone who installs Ludo can extract it and
# read this repo's source. Nothing else may be reachable with it.
#
# Writes app/ludo_app/_token.py, which is gitignored. Run it after checkout and
# before packaging; run with --clear afterwards so a dev machine doesn't keep
# the token lying around.
set -euo pipefail

out="$(dirname "$0")/../app/ludo_app/_token.py"

if [[ "${1:-}" == "--clear" ]]; then
    rm -f "$out"
    echo "cleared $out"
    exit 0
fi

: "${GH_RELEASE_TOKEN:?set GH_RELEASE_TOKEN to the fine-grained read-only PAT}"

# Split into chunks so the literal never appears whole in the file — enough to
# defeat secret scanners and casual grep, and nothing more. See release_token.py.
python3 - "$GH_RELEASE_TOKEN" > "$out" <<'PY'
import sys
t = sys.argv[1].strip()
parts = [t[i:i + 7] for i in range(0, len(t), 7)]
print('"""Generated by scripts/embed-token.sh. Not in git. Do not edit."""')
print('TOKEN = (')
for p in parts:
    print(f'    {p!r},')
print(')')
PY

echo "wrote $out ($(wc -c < "$out") bytes)"
